- LICENSE.md
- licenses/APL.txt
- licenses/DCL.txt
> Add licenses

- content/howto/concurrent-modification-java-multithreaded.md
Easy navigation and easy reading for others.
> Fix broken url in docs

- scripts/build.sh
> Fix issue in netlify

- scripts/build.sh
Make the tag independent from the version variable.
It was creating folders with v20.11.0 instead of just v20.11
> Fix Hugo build

- scripts/build.sh
> Fix docker tags

- content/get-started/index.md
> Remove hardcoded version

- content/howto/retrieving-debug-information.md
> Add debuginfo command docs

- content/deploy/dgraph-administration.md
- content/deploy/download.md
- content/deploy/kubernetes.md
- content/enterprise-features/binary-backups.md
- content/howto/dgraph-sentry-integration.md
> 20.11: Update manual version references (#20)

- content/deploy/dgraph-administration.md
- content/deploy/download.md
- content/deploy/kubernetes.md
- content/howto/dgraph-sentry-integration.md
> Update manual version references 20.07 (#20)

- content/howto/concurrent-modification-java-multithreaded.md
> sync 20.11 with master

- content/clients/unofficial-clients.md
* dgraph4net client supports ASP.NET Identity and recursive persistence.
> docs(clients): Add dgraph4net C# client to unofficial clients

- content/graphql/mutations/update.md
> docs (Update): Add note about remove behavior

- content/howto/completion.md
> Document completion command

- content/faq/index.md
With this the link would go straight to the [list](https://github.com/dgraph-io/badger#projects-using-badger) rather than the [Badger repo](https://github.com/dgraph-io/badger).
> Docs(Other): Update link to the list of projects using Badger

- content/deploy/dgraph-alpha.md
Also includes editing of the introduction sentence.
> Chore(Other): Remove outdated deprecation notice from Dgraph Alpha docs

- content/clients/go.md
> Docs(clients): update the Go client complete example

- content/clients/go.md
> docs(clients): Update go.md (#43)

- content/enterprise-features/lsbackup.md
> docs(CLI): Add documentation for lsbackup command

- content/enterprise-features/lsbackup.md
> docs(CLI): Add lsbackup

- content/enterprise-features/lsbackup.md
Fix DOC-81
* docs(CLI): Add documentation for lsbackup command (#41)
> docs(CLI): Add lsbackup (#48)

- content/graphql/directives/index.md
> docs(chore): Fix broken link on Directives article

- content/graphql/lambda/field.md
- content/graphql/lambda/mutation.md
- content/graphql/lambda/overview.md
- content/graphql/lambda/query.md
> docs (update): improve lambda articles (#32)

- content/deploy/fast-data-loading/bulk-loader.md
- content/deploy/fast-data-loading/live-loader.md
> docs(loader): Add S3 and minio to bulk/live loader

- content/deploy/dgraph-administration.md
Update of exports section under deploy administration:
* update new `destination` input for object stores with MinIO and S3.
* reorganized sections for configuration of existing features
* update encryption-at-rest, added exports config tip
(cherry picked from commit aca9ef14d526e2cdcdbb79784b8a21c95e07451b)
> Docs(Deploy): updated deploy / administration / exports section (#60)

- content/_index.md
- content/deploy/_index.md
- content/deploy/admin/_index.md
- content/deploy/cluster-checklist.md
- content/deploy/cluster-setup.md
- content/deploy/config.md
- content/deploy/data-compression.md
- content/deploy/dgraph-administration.md
- content/deploy/dgraph-alpha.md
- content/deploy/dgraph-zero.md
- content/deploy/download.md
- content/deploy/fast-data-loading/_index.md
- content/deploy/kubernetes.md
- content/deploy/log-format.md
- content/deploy/ludicrous-mode.md
- content/deploy/metrics.md
- content/deploy/monitoring.md
- content/deploy/multi-host-setup.md
- content/deploy/overview.md
- content/deploy/ports-usage.md
- content/deploy/production-checklist.md
- content/deploy/security/_index.md
- content/deploy/single-host-setup.md
- content/deploy/tls-configuration.md
- content/deploy/tracing.md
- content/dgraph-overview.md
Cherry-pick from PR #47 to 20.11 docs
* Add overview
* Add "admin" and "security" sub-sections, reorganize left-nav
* Update overview.md
* Updated to improve clarity, incorporate feedback:
* backups -> exports (per reviewer feedback)
* Move files and change refs to avoid 404s or redirects
* Fix links, avoid 404s
* Update "deploy" card on docs landing page
* Link from Dgraph Overview to Deployment and Management Overview
> [Cherry-Pick PR #47] Docs(Deployment and Management): Add a high-level overview, reorganize this section, add sub-sections 

- content/_index.md
Approved over Slack by @moonstormer and @zhenniwu
> Nav(Tour linkage): add a prominent link to dgraph.io/tour, targeted at those new to Dgraph

- content/enterprise-features/multitenancy.md
> docs (enterprise): Create documentation for multi-tenancy

- content/enterprise-features/learner-nodes.md
> docs (enterprise): Documentation for read replicas (learner nodes)

- content/deploy/metrics.md
Documentation per https://github.com/dgraph-io/dgraph/pull/7338 (see the "Raft leadership metrics" section) and https://github.com/dgraph-io/dgraph/pull/7339 (see additions to "Health metrics")
Also, this PR reorganizes metric categories (alphabetized, no break-up of existing category contents), updates introduction, corrects headers, adds SEO.
Fixes DOC-166 and DOC-165
Staged here: https://deploy-preview-78--dgraph-docs-repo.netlify.app/deploy/metrics/
> Docs(Metrics): 21.03 feature documentation for Transaction and Raft metrics

- content/enterprise-features/binary-backups.md
> docs (chore) Remove restoreId and restoreStatus

- content/enterprise-features/_index.md
added new cards for:
- audit logs
- multi-tenancy
- learner node
> Add overview for new 21.03 new EE features

- content/deploy/fast-data-loading/bulk-loader.md
- content/deploy/fast-data-loading/live-loader.md
- content/enterprise-features/multitenancy.md
> docs (enterprise): Update multi-tenancy docs

- content/graphql/api/fragments.md
Needs to be cherry-picked to v20.11 and v20.07.
> chore(GraphQL): Fix title typo.

- content/graphql/schema/ids.md
Cherry-pick of https://github.com/dgraph-io/dgraph-docs/pull/34 from the release/v20.11 branch.
> Cherry-Pick: docs(GraphQL): Add paragraph around combining ID with @id

- content/enterprise-features/access-control-lists.md
* fix 6 queries (syntax errors, api errors)
* doc structure reorganization
* updated docker-compose example, added helm chart
* updated login section, added curl command
(cherry picked from commit 892fe0b27c330bed8571886e9b6c279466d62424)
> chore(fix): ACL update (#95)

- content/deploy/troubleshooting.md
Update to "Troubleshooting" section on OOM issues
- Fixes DOC-178
- Includes some rewording for style, clarity, and ease of translation throughout the file
- Checked for preexisting spelling issues (`aspell check troubleshooting.md`)
> Docs(Troubleshooting): 21.03 documentation on how to use new `goroutines` option to troubleshoot OOM issues

- content/enterprise-features/access-control-lists.md
> docs(enterprise): Add Vault to access-control-lists.md

- content/clients/csharp.md
- content/clients/go.md
- content/clients/javascript/grpc.md
- content/clients/python.md
> docs(clients): Add Slash connection examples

- content/graphql/authorization/authorization-overview.md
> docs(graphql): Add authorization standard claims notes

- content/enterprise-features/learner-nodes.md
> docs(chore): add note to learner nodes

- content/enterprise-features/access-control-lists.md
- content/enterprise-features/binary-backups.md
- content/enterprise-features/change-data-capture.md
- content/enterprise-features/encryption-at-rest.md
- content/enterprise-features/learner-nodes.md
- content/enterprise-features/license.md
- content/enterprise-features/lsbackup.md
- content/enterprise-features/multitenancy.md
Documentation based on information tracked in/linked from DOC-158 and SUCCESS-346, and from KT session notes.
Fixes DOC-158
> Docs (Change Data Capture): Add documentation for CDC feature introduced in 21.03

- content/deploy/config.md
This update does the following:
* toml, properties, and hcl config file formats.
* introduces superflags
* documents json and yaml using superflags
> chore(update): config docs w/ superflags

- content/graphql/mutations/add.md
- content/graphql/mutations/deep.md
- content/graphql/mutations/delete.md
- content/graphql/mutations/update.md
Fixes minor typos and minor formatting changes.
> Chore (Other): Fix typos and misc.

- content/graphql/authorization/directive.md
> Fix Auth Query Rule Example

- content/howto/retrieving-debug-information.md
1. Updated the docs to reflect the implementation that will be introduced by https://github.com/dgraph-io/dgraph/pull/7439
2. minor fixes
> Add new metrics collected by debuginfo

- content/howto/retrieving-debug-information.md
1. Updated the docs to reflect the implementation that will be introduced by https://github.com/dgraph-io/dgraph/pull/7439
2. minor fixes 
(cherry picked from commit 3d9d22ff5e6f0fc72626f195f57ff2c844bd284b)
> cherry pick debuginfo update

- content/graphql/custom/directive.md
- content/graphql/directives/index.md
> docs(graphql): add remoteResponse directive

- content/_index.md
> Docs (Linking) Add prominent links to Dgraph Cloud and installation links from dgraph.io/docs homepage

- content/graphql/queries/search-filtering.md
- content/graphql/schema/search.md
> docs(graphql): Update IN filter documentation

- content/enterprise-features/license.md
This PR contains the warning message texts related to license expiry. Users who implement log monitoring tools can use the text patterns documented in this PR to set up alerts for themselves.
> docs(license): Warning messages related to license expiry

- content/query-language/type-system.md
> docs(DQL): Add type query example

- content/graphql/subscriptions/index.md
> Docs (GraphQL Subscriptions): Rewording for style, plus gzip compression support

- content/graphql/lambda/mutation.md
> docs(graphql): Add lambda dql.mutate example

- content/enterprise-features/multitenancy.md
> docs(EE): Add listing namespaces to multitenancy

- content/enterprise-features/multitenancy.md
> docs(chore): Fix "delete namespace" example

- content/graphql/schema/types.md
> docs(chore): Add note regarding password type

- content/enterprise-features/_index.md
Adding CDC card overview in https://dgraph.io/docs/master/enterprise-features/
> Add cdc card in the ee overview

- content/enterprise-features/multitenancy.md
> docs (EE): Add FAQ to multitenancy article

- content/graphql/schema/migration.md
> docs(graphql): Create schema migration article

- content/graphql/authorization/authorization-overview.md
> docs(graphql): Add JWK URLs to Authorization overview

- content/enterprise-features/audit-logs.md
> docs(EE): Add an audit log example

- content/enterprise-features/multitenancy.md
> docs(EE): Update multitenancy with query-limit notes

- content/graphql/directives/index.md
- content/graphql/queries/search-filtering.md
- content/graphql/schema/deprecated.md
> docs(graphql): Add deprecated directive

- content/graphql/admin/index.md
> docs(graphql): Remove CORS and schema history

- content/deploy/dgraph-administration.md
> docs: Add migration information (20.11 to 21.03)

- content/enterprise-features/learner-nodes.md
> Docs (Learner Nodes): Add --my flag, plus minor updates (reduction in code font, some minor rewording)

- content/enterprise-features/access-control-lists.md
Superflag environment variables don't need quotation marks.
> Chore(ACL): Fix typos in example configs.

- content/enterprise-features/access-control-lists.md
> Chore(ACL): Quote Docker Compose ports section.

- content/enterprise-features/access-control-lists.md
* quotes for ports
*  version for containers to v20.11.3
> docs(acl) -  fixes in v20.11 

- content/enterprise-features/multitenancy.md
> docs(chore): Fix multitenancy reference

- content/get-started/index.md
* fix alter schema where wrong time was using for starring and director
* update curl commands to use long form and make them consistent
* quotes on docker command to make arg values stand out 
* put comment on standalone as tooltip
> docs(getting-started): get-started update: alter schema fix, add order to query, curl commands

- content/get-started/index.md
* fix alter schema where wrong time was using for starring and director
* update curl commands to use long form and make them consistent
* quotes on docker command to make arg values stand out
* put comment on standalone as tooltip
(cherry picked from commit 3fbd6ac5ae1f200adb96d066dbc6365b5451aab9)
> docs(get-started) - fix schema, update curl commands and tooltip

- .github/workflows/deployments.yml
- content/clients/go.md
- content/clients/java.md
- content/clients/javascript/grpc.md
- content/clients/javascript/http.md
- content/graphql/_index.md
- content/graphql/queries/cascade.md
- content/graphql/schema/migration.md
- content/howto/upserts.md
- content/query-language/indexing-custom-tokenizers.md
- content/tutorial-8/index.md
> Added misspell github action

- content/deploy/cli-command-reference.md
> docs(flags): update badger flags

- content/query-language/math-on-value-variables.md
> docs(chore): Add note about math operations

- content/releases/index.md
> docs(chore): Update release notes

- content/clients/javascript/http.md
> docs(clients): Add Cloud client example for js-http

- content/clients/python.md
> docs(chore): Update python client docs

- content/clients/python.md
> docs(client): update Python client

- content/enterprise-features/multitenancy.md
> docs(EE): Update multitenancy example

- content/enterprise-features/multitenancy.md
> docs(chore): cherry-pick to 21.03

- content/enterprise-features/change-data-capture.md
> docs(chore): Fix change-data-capture.md

- content/deploy/fast-data-loading/live-loader.md
- content/enterprise-features/multitenancy.md
this PR fixes some wrong statements/commands in our current multi-tenancy doc
> Multi-tenancy fixes

- README.md
- config.toml
- netlify.toml
- scripts/build.sh
> docs(chore): theme update (20.07)

- README.md
- config.toml
- netlify.toml
- scripts/build.sh
> docs(chore): theme update (21.03)

- content/clients/go.md
- content/clients/java.md
- content/clients/javascript/grpc.md
- content/clients/python.md
> docs(clients): Add example code to deprecate DialSlash

- content/clients/go.md
- content/clients/java.md
- content/clients/javascript/grpc.md
- content/clients/python.md
> docs(clients): Add DialCloud methods to client docs

- CODE_OF_CONDUCT.md
> docs(chore): Create CODE_OF_CONDUCT.md

- content/graphql/lambda/field.md
- content/graphql/lambda/overview.md
> Docs (chore) minor edits to PR#205

- content/clients/unofficial-clients.md
@bucanero as you requested here is the PR for the master branch
> Docs(Unofficial Dgraph Clients): Add dqlx as unofficial client

- content/graphql/schema/dgraph-schema.md
> docs(graphql): Update Dgraph GraphQL schema

- content/dgraph-overview.md
- content/query-language/graphql-fundamentals.md
> Docs (Chore) Make Dgraph Overview cloud-first, note how to determine the Dgraph Cloud version of a given backend, and how to view docs for it

- content/deploy/dgraph-administration.md
- content/deploy/dgraph-alpha.md
- content/enterprise-features/binary-backups.md
- content/graphql/admin/index.md
> docs(admin): Add new admin task API

- content/deploy/fast-data-loading/bulk-loader.md
> docs(fix): Add missing flags to bulk-loader.md

- content/graphql/authorization/mutations.md
- content/graphql/overview/index.md
Edit pass on the "Mutations" topic within GraphQL Authorization:
* todos -> to-do list items
* General style fixes
> Docs (Edit Pass): update wording and improve SEO for "Mutations and GraphQL Authorization"

- content/query-language/cascade-directive.md
> docs(DQL): Add parameterized cascade directive

- content/deploy/troubleshooting.md
> docs(deploy): Update ulimit troubleshooting notes

- content/deploy/dgraph-administration.md
> docs(fix): Update mutations superflag

- content/graphql/authorization/directive.md
> Style Edit Pass: "The @auth Directive"

- content/clients/javascript/grpc.md
> Docs (Chore): Note that the Dgraph JavaScript gRPC client now uses grpc-js, following deprecation of the official grpc JavaScript client

- content/query-language/cascade-directive.md
> docs(DQL): Add cascade performance notes

- content/deploy/fast-data-loading/live-loader.md
This refreshes S3 bucket content as well as some other clean-up
* converted short flags to long flag, as long-form flags are self documenting, which is good for documentation
* updated <meta-strings> to be consistent
* change reference to bulk loader to live loader for live loader documentation
* vertically stacked long command line examples that were greater than 150 columns, so that readers don't have to constantly scroll horizontally
* documented both long form s3://s3.<region>.amazonaws.com/<bucket-name> and short form s3:///<bucket-name> examples
* added notes that short form s3 URL requires triple slash (s3:///) as this is something easily missed
* normalize subtitles where appropriate to style guide
> Docs(liveloader): update for s3 buckets and cleanup

- content/get-started/index.md
> docs(fix): Remove Github issues link

- content/graphql/authorization/directive.md
> docs(graphql): Update Auth rules example

- .gitignore
- content/graphql/authorization/directive.md
> doc(fix): Elaborate and correct auth directive examples (DOC-234)

- content/graphql/dgraph/index.md
> docs(graphql): Update mapping Graphql to Dgraph

- content/graphql/dgraph/index.md
> Docs(graphql): Add note regarding schema migration

- content/deploy/dgraph-administration.md
- content/deploy/dgraph-alpha.md
- content/enterprise-features/binary-backups.md
- content/graphql/admin/index.md
> docs(cp): Add new admin Task API docs

- content/dgraph-overview.md
Hi @danielmai and @verneleem! I don't have write access to dgraph-io/dgraph-docs any more, and my review of PR #246 required a commit, so please use this PR to review and merge my feedback on the updates to the overview by @verneleem
> Docs (Dgraph Overview) Editorial review for dgraph-docs PR # 246

- content/graphql/queries/cascade.md
> Docs(GraphQL) Add example of using filter with @cascade

- content/howto/lambda-webhooks-example.md
> Minor fix to language

- content/graphql/queries/order-page.md
Cherry-pick of #270 into the master branch.
> Say the order parameter is not required for pagination.

- content/releases/index.md
* Update the Releases page with the latest release, Dgraph v21.12 Zion.
* Update the previous versions' patch release information.
* Remove support for v20.07 and v20.11.
> docs(release): Dgraph v21.12 Zion release.

- content/dgraph-overview.md
Fix a typo in "Dgraph Overview".
> Docs(Other): Fix a typo in "Dgraph Overview"

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/deployments.yml
- README.md
- content/_index.md
- content/clients/java.md
- content/clients/javascript/grpc.md
- content/clients/python.md
- content/deploy/kubernetes.md
- content/deploy/multi-host-setup.md
- content/deploy/production-checklist.md
- content/deploy/single-host-setup.md
- content/deploy/tls-configuration.md
- content/enterprise-features/access-control-lists.md
- content/enterprise-features/encryption-at-rest.md
- content/enterprise-features/license.md
- content/faq/index.md
- content/get-started/index.md
- content/graphql/admin/index.md
- content/graphql/mutations/add.md
- content/graphql/mutations/delete.md
- content/graphql/mutations/mutations-overview.md
- content/graphql/mutations/update.md
- content/graphql/mutations/upsert.md
- content/graphql/overview/index.md
- content/graphql/quick-start/index.md
- content/graphql/todo-app-tutorial/todo-schema-design.md
- content/howto/concurrent-modification-java-multithreaded.md
- content/query-language/schema.md
- scripts/build.sh
- scripts/local.sh
Some scripts may break if you don't rename master to main.
> Chore(Other): Migration from master to main

- content/enterprise-features/change-data-capture.md
Add some missing requirements and a flag that was overlooked
> Docs(CDC): Update Kafka CDC instructions

- content/deploy/download.md
Description: 
Closes #298. Update install from source steps to follow latest readme (https://github.com/dgraph-io/dgraph/blob/matthewmcneely/update-readme-and-contributing/README.md).
> Docs(Download): Update install from source steps to follow readme

- content/deploy/fast-data-loading/bulk-loader.md
> Chore(Other): Fix broken link

- content/deploy/tls-configuration.md
> Chore(Other): Fix broken link 2

- content/deploy/dgraph-administration.md
> Chore(Other): Fix port typo

- scripts/build.sh
> chore(build): ostracize v21.12

- scripts/build.sh
updating version to release v22
> fix(docs): update version

- scripts/build.sh
update the array list to handle 2103
> fix(doc) Update build.sh

- scripts/build.sh
> fix(ci): Update build.sh

- content/enterprise-features/access-control-lists.md
- content/enterprise-features/encryption-at-rest.md
- content/releases/index.md
- scripts/build.sh
Addresses the issue: 
https://github.com/dgraph-io/dgraph-docs/issues/305
_added instructions to generate random key values
Note: Create and edit docs in the `main` branch when you can, so that we only cherry-pick out of `main`, not into `main`.
-->
Fixes: https://github.com/dgraph-io/dgraph-docs/issues/305
> [update] Enabling ACL

- content/releases/index.md
latest version in V22.0.x serie is v22.0.2 update table and link
> Chore(Other):add v22.0.2 in releases list

- .github/CODEOWNERS
- netlify.toml
try path prefix with / to avoid // on url
> Algolia main

- config.toml
- netlify.toml
- scripts/branchdeploy.sh
> upgrade hugo version to 0.91

- config.toml
- netlify.toml
- scripts/branchdeploy.sh
handle main as a branch deploy in netlify, update hugo version
> updat ehugo version and netlify config

- config.toml
- netlify.toml
- scripts/build.sh
master is now used to build doc for a list of releases and for main into a single netlify site.
> update build script

- config.toml
- netlify.toml
- scripts/branchdeploy.sh
we are using a new branch deploy script  for releases
> V21.12 hugo 91

- netlify.toml
- scripts/build.sh
> correct version list

- netlify.toml
- scripts/build.sh
we need to generate in public and also in public/docs for the crawler
> change latest release build

- content/enterprise-features/audit-logs.md
Documentation provides incorrect flag. See L57-75 in ee/audit/run_ee.go.
> update audit-logs.md encrypt flag (#288)

- content/dql-syntax/json-mutation-format.md
remove reference to RDF.
Remove explanation aout curl and HTTP client.
Clarify JSON examples.
fixes #481
> [REVAMP]: clean json mutation document

- .github/styles/Vocab/Dgraph/accept.txt
- content/graphql/security/mutations.md
Fix grammar errors
Based on #211
> chore(typos): Fix grammar errors

- content/query-language/cascade-directive.md
> docs(DQL): Add cascade performance notes (#227)

- content/query-language/math-on-value-variables.md
The query in question was out of date. 5 years have passed. And with that its logic started to ignore all results due to that(the years). The solution was to change from 10 years to 20 years. 
I believe that in another 5 or 10 years we will need to update again LOL
> Docs(DQL):  Update and fix an old query.

- content/dgraph-overview.md
> Docs: Fix shared instance link

- content/dgraph-overview.md
- content/dgraphcloud/introduction.md
reference Dgraph database overview and update wording.
> update cloud intro

- content/deploy/cli-command-reference.md
- content/enterprise-features/binary-backups.md
For PR https://github.com/dgraph-io/dgraph/pull/7603
Closes: DGRAPHCORE-278
> add docs for alpha option max-pending-queries

- content/graphql/schema/directives/directive-withsubscription.md
- content/graphql/subscriptions/index.md
add example using URQL and subscriptions-transport-ws
> update graphql subscription doc

- content/graphql/security/jwt.md
Add an example of Dgraph.Authorization configuration with Clerk.com auth provider.
> add Clerk.com config example
