dgraph-io/dgraph-docs

.gitignore
scripts/build.sh

```
bash ./scripts/build.sh
Thu Jan 21 02:50:03 -03 2021  Starting to check branches.
error: pathspec 'release/v20.11.0' did not match any file(s) known to git
Thu Jan 21 02:50:05 -03 2021  Updating docs for branch: release/v20.11.0.
version => 'v20.11'
latest_version => 'v20.11.0'
error: Your local changes to the following files would be overwritten by checkout:
scripts/build.sh
Please commit your changes or stash them before you switch branches.
Aborting
Thu Jan 21 02:50:06 -03 2021  Updating docs for branch: master.
version => 'master'
latest_version => 'master'
error: pathspec 'release/v20.07.3' did not match any file(s) known to git
Thu Jan 21 02:50:07 -03 2021  Updating docs for branch: release/v20.07.3.
version => 'v20.07'
latest_version => 'v20.07.3'
error: Your local changes to …
```

fix: Fix bug with the docker tag in docs.

---

content/howto/login-system.md

Using v20.11.0 the how-to guide seems outdated as the returned json does not match with the defined struct and leads to index out of range panics when accessing the not existing "Pass" field.

How-To-Guide: update and correct "Simple Login System"

---

scripts/build.sh

Before merge: It depends on https://github.com/dgraph-io/hugo-docs/pull/86.

Make the version tag independent.

---

content/deploy/dgraph-administration.md
content/deploy/download.md
content/deploy/kubernetes.md
content/enterprise-features/binary-backups.md
content/enterprise-features/encryption-at-rest.md
content/howto/dgraph-sentry-integration.md
content/migration/migrate-dgraph-1-1.md

Update manual version references

---

content/howto/load-balancing-nginx.md

Our current documentation is focused on showing how to set up nginx lb with docker-compose.
This documentation PR will be useful for users what to set up nginx lb and are starting their Dgraph Cluster using a different deployment method (like systemd)
This is a cherry-pick like from dgraph-io/dgraph#7291

v20.07 - nginx lb for Dgraph Cluster that are not started with docker-compose

---

content/howto/load-balancing-nginx.md

Our current documentation is focused on showing how to set up nginx lb with docker-compose.
This documentation PR will be useful for users what to set up nginx lb and are starting their Dgraph Cluster using a different deployment method (like systemd)
This is a cherry-pick like from https://github.com/dgraph-io/dgraph/pull/7291

v20.11 - nginx lb for Dgraph Cluster that are not started with docker-compose

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

This PR updates the dgraph-docs repo with a new readme and pull request template that provides more detailed contributor guidelines, including:
- How to title PRs
- Information to include in the description
- Which branches to target for doc development (use `master` when possible)
- Style guide information
- Minor edits throughout
- Removed outdated "deployment" section
Fixes DGRAPH-2917
Cherry-Pick to all release/* branches.

Docs (Repo Readme): Update the dgraph-docs repo readme file and PULL_REQUEST_TEMPLATE.md with contributor guidelines

---

content/graphql/authorization/directive.md

Fixes the broken link to the `@secret` directive reference [here](https://dgraph.io/docs/graphql/authorization/directive/).
Cherry-pick to 20.11 and 20.07

Docs(Other): Fix broken link for @secret

---

content/graphql/schema/ids.md

- Add information on relationship between ID and @id
- Add example of get query when using `@id` directive
- Typo fixes
- Rephrased a sentence that was using `id` in the @id directive paragraph.
@aaroncarey patched commits 2-5 to edit the full page for TW style, improve the introduction, and move a forward-looking statement to the comments.
Fixes DOC-115

docs(GraphQL): Add paragraph around combining ID with @id

---

content/graphql/authorization/authorization-overview.md

This documents the ClosedByDefault setting in the Dgraph.Authorization
object. This was introduced in Dgraph v20.11.0 in dgraph-io/dgraph#6779.
Fixes DOC-134
Related:
https://discuss.dgraph.io/t/implemented-queries-closed-by-default/12626

docs(graphql): Document ClosedByDefault setting for authorization.

---

content/graphql/lambda/overview.md

Added addGraphQLResolvers and addMultiParentGraphQLResolvers type definitions to the documentation overivew.
After pondering some a week about what kind of examples would add value, and not really landing on anything specific, I decided it would be best to better describe the functions and passed through parameters with type definitions. This allows a developer to better understand all of the possibilities without an actual example for each specific use case in the docs.
These type definitions were reduced into a simple form from https://github.com/dgraph-io/dgraph-lambda/blob/master/slash-graphql-lambda-types/types.d.ts

Docs(GraphQL): added type definitions to resolver functions and arguments.

---

content/graphql/lambda/field.md
content/graphql/lambda/mutation.md
content/graphql/lambda/overview.md
content/graphql/lambda/query.md

docs (update): improve lambda articles

---

content/graphql/dgraph/index.md
content/graphql/directives/index.md

chore(graphql): Move article back to GraphQL section

---

content/graphql/dgraph/index.md
content/graphql/directives/index.md

Move article back to GraphQL (#54)

---

content/clients/_index.md

Fixed issue where hugo server would not start due to missing link.
```
ERROR 2021/02/12 17:30:27 [en] REF_NOT_FOUND: Ref "javascript.md": "/Users/joaquin/workarea/dgraph-docs/content/clients/_index.md:55:14": page not found
```

Other: updated client reference to javascript bad link broke hugo

---

content/clients/javascript/grpc.md

This was changed in the client by PR: https://github.com/dgraph-io/dgraph-js/commit/18bc38f6eac782386bfda4c90893a36be586311b#diff-009952dc4ac10bec7174ab1e2024ac38bb7adbc0eb1dbd2050a8c789466933ba
This was discussed in topic: https://discuss.dgraph.io/t/working-grpc-example-with-slash-graphql/9628/9

Docs(GraphQL) add Slash grpc connection method and example.

---

README.md

This updates instructions (`README.md`) to use hugo 0.74.x in order to match what prod build uses.

Chore(other) - version bump hugo to v0.74.x

---

content/query-language/sorting.md

docs (sort): Add notes about null values on sort queries

---

content/deploy/dgraph-administration.md

The primary purpose of this PR is to update new features, e.g. object storage, that are not yet documented for Dgraph Alpha export functionality.  The secondary purpose is to clean up the organization and give users a comprehension guide to use Dgraph Alpha export.
This PR adds the following:
* added section on object storage
* added section to use MinIO gateway to Azure storage blob and Google Cloud Storage
* added section to use curl command with GraphQL
* added section for anonymous 
* added section on how to turn off default HTTPS
* updated using `destination` for file paths, and put this under its own section.
* updated content on configuration Dgraph Alpha server configuration for `--exports` and placed this in its own identifiable section.
* added an example of how to run Dgraph …

Docs(Deploy): updated deploy / administration / exports section

---

scripts/build.sh

This will collect the major versions from https://get.dgraph.io/latest
This will make the version list be automated based on Github API data treated in https://get.dgraph.io/latest

chore: Automate the versioning docs based on Github API

---

content/graphql/queries/and-or-not.md

Also fixed a typo from `eg` to `eq` that caught my eye.
This change was implemented in 20.11 to coerce types into lists and specifically allow the `and` and `or` filter to be a list of filters. It was not clearly stated in the changelog, but can be found in these discuss posts:
https://discuss.dgraph.io/t/there-can-be-only-one-input-field-named/8384/9
https://discuss.dgraph.io/t/limitations-of-graphql-nested-filters/10798

Docs(GraphQL) add list coercion documentation and example.

---

content/howto/migrate-dgraph-1-1.md

Cherry-pick of https://github.com/dgraph-io/dgraph/pull/7179 from `dgraph` repo to `dgraph-docs` repo's 20.07 branch. 
Reframes this content as migration from v1.0, instead of migration to v1.1

[Cherry-Pick master -> release/v20.07]: Docs(Migration): "Migrate from Dgraph v1.0 to Newer Versions" #7179

---

content/deploy/log-format.md
content/enterprise-features/audit-logs.md

Staged here: https://deploy-preview-74--dgraph-docs-repo.netlify.app/enterprise-features/audit-logs/
Fixes Doc-159

Docs(audit logs): Add documentation for audit logging capabilities enabled with enterprise license

---

content/query-language/graphql-fundamentals.md

This PR adds the two types of code error you would get from the /query endpoint
(cherry picked from commit 1ad62b68da4749de5f668c5de0420e3941ff8b8e)

[v20.11 cherry-pick]  Add "code" messages errors for "/query" endpoint (#76)

---

content/query-language/graphql-fundamentals.md

This PR adds the two types of code error you would get from the /query endpoint
(cherry picked from commit 1ad62b68da4749de5f668c5de0420e3941ff8b8e)

[v20.07 cherry-pick]  Add "code" messages errors for "/query" endpoint (#76)

---

content/enterprise-features/access-control-lists.md

This is update for Enterprise ACL rules fixes 6 queries and other updates:
* fixed graphql queries
* updated all queries to have consistent style
* fixed removing rules as use of API was incorrect (example did not work)
* fixed remove user from group as syntax did not parse
* fixed add rule to alice user as syntax did not parse
* fixed remove rule from group as syntax did not parse
* fixed delete user as syntax did not parse
* fixed delete group as syntax did not parse
* updated check dev group (getGroup) to add implicit keyword `query`
* removed licensing info as out of scope for ACLs (should be in overview or other page)
* removed `dgraph acl` command line documentation
* updated enabling ACL section
* added `whitelist` that is required to use ACLs
* removed unnecessary flag options …

chore(fix): ACL update

---

content/clients/java.md
content/deploy/overview.md
content/dgraph-overview.md
content/graphql/todo-app-tutorial/deploy.md

Renaming slash.dgraph.io -> cloud.dgraph.io everywhere

---

content/graphql/mutations/add.md
content/graphql/mutations/upsert.md
content/howto/upserts.md

Documentation for GraphQL upserts as per PR: https://github.com/dgraph-io/dgraph/pull/7433.
Fixes [DOC-167](https://dgraph.atlassian.net/browse/DOC-167).
Preview [here](https://deploy-preview-88--dgraph-docs-repo.netlify.app/graphql/mutations/upsert/).

Docs (GraphQL): 21.03 feature documentation for GraphQL Upserts

---

content/deploy/config.md

Configuration refresh.
* expanded examples for config file formats, environment vars, and command line flags.
* config files have examples have string, boolean, int
* config files have examples flat dot `.` notation to key:hash 
* env vars have example with flag with a dot `.`
* specific flags chosen, so that update super-flags can be more easily compared
* put config file examples under their own heading so that navigation is easier (bulleted list on the right side)
* removed lru example, as that is deprecated
Not Goal
* v21.03.0 and super flags.  This will be a follow up PR, so that this commit can cherry-picked to earlier versions.

chore(fix) - update config 

---

content/graphql/schema/ids.md

Documentation for using multiple `@id` fields in a type as per PR: https://github.com/dgraph-io/dgraph/pull/7235.
Addresses [DOC-170](https://dgraph.atlassian.net/browse/DOC-170).

Docs (GraphQL): 21.03 feature documentation for multiple @id fields in a type

---

content/enterprise-features/access-control-lists.md

Update to support compound flags:
* command line references
* environment variables references including docker-compose file
* config file references including helm chart values (changed from toml to yaml)

docs(ACL): update to support new compound flag format

---

content/graphql/admin/index.md

Fixes GRAPHQL-1085
This PR adds a tip about the errors during GraphQL schema update which should be retried by the user.

Docs(GraphQL): Add a tip about errors during schema update

---

content/deploy/cli-command-ref.md
content/deploy/troubleshooting.md

Added information on new flags and options, and how they map to earlier flags, per https://github.com/dgraph-io/dgraph/pull/7436, https://github.com/dgraph-io/dgraph/pull/7491, and https://github.com/dgraph-io/dgraph/pull/7544
Also, added a "Dgraph CLI Command Reference", per prior discussion with @OmarAyo.
Staged here: https://deploy-preview-111--dgraph-docs-repo.netlify.app/deploy/cli-command-ref/
Fixes DOC-168

Docs (Superflags) document new flags and options added in 21.03 as part of a CLI Command Reference

---

content/graphql/mutations/update.md

docs(chore): Update note on empty mutation

---

content/graphql/directives/index.md
content/graphql/lambda/server.md
content/graphql/lambda/webhook.md

Docs regarding lambda webhooks.
Fixes DOC-199

Docs (GraphQL): 21.03 feature documentation for lambda webhooks

---

content/graphql/federation/index.md

Docs regarding support for Apollo federation.
Fixes DOC-156

Docs (GraphQL): 21.03 feature documentation for federation

---

content/clients/go.md
content/clients/java.md
content/clients/javascript/grpc.md
content/clients/python.md

docs(clients): Add multi-tenancy to Dgraph client docs

---

content/graphql/queries/search-filtering.md

Documents usage of `has` filter with a list of fields, as per PR: https://github.com/dgraph-io/dgraph/pull/7363 
Addresses [DOC-219](https://dgraph.atlassian.net/browse/DOC-219).
Preview [here](https://deploy-preview-134--dgraph-docs-repo.netlify.app/graphql/queries/search-filtering/#filter-for-objects-with-specified-non-null-fields-using-has).

Docs (GraphQL): Add documentation for has filter on list of fields

---

content/enterprise-features/audit-logs.md

This PR fixes the following typos in the audit log doc page:
- `dir` has been renamed to `output`
- `encypt_file` to `encrypt-file`

Audit logs - fix commands 

---

content/graphql/queries/cascade.md

docs(graphql): Add pagination notes to Cascade

---

content/graphql/queries/cascade.md

docs(graphql): add note about pagination

---

content/deploy/production-checklist.md

* Fixes the wrong serial name in the "Set up Dgraph Alpha Group" section. 
* Also adds separate hyperlinks to Metrics and Monitoring page.

Chore (Deploy): Minor fixes

---

content/clients/csharp.md

docs(clients): Add multi-tenancy example to C#

---

content/deploy/metrics.md
content/deploy/production-checklist.md
content/deploy/single-host-setup.md
content/deploy/tls-configuration.md
content/dgraph-overview.md
content/howto/completion.md
content/mutations/json-mutation-format.md

Per DOC-141
Note that the docker standalone command was taken from the Tour (https://dgraph.io/tour/intro/2/), and was validated using the command shown there:
docker run -it -p 5080:5080 -p 6080:6080 -p 8080:8080 \
-p 9080:9080 -p 8000:8000 -v ~/dgraph:/dgraph --name dgraph \
dgraph/standalone:v20.11.0
After validating this with 20.11.0, I updated it to reference v.21.03.0
Also includes manual spellcheck (`aspell check -M -x filename.md`) on all updated files

Docs (Chore): Update to reflect Windows and MacOS deprecation, include Docker standalone instructions

---

content/graphql/lambda/server.md

This copose spec has several advantages over the current example like: 
- It uses the same draph image as all the other examples to start Dgraph alpha + zero 
- I've removed the (version) in the compose spec since that's not required anymore given the latest compose spec updates
- I'm using env variables to set the correct lambda URL instead of using custom arguments .

Docs(Lambda): Use a better compose file for dgraph + lambda

---

content/enterprise-features/encryption-at-rest.md

* Adds in-page link to the section describing the usage of `--vault` supeflag for encryption. 
* Fixes a "repeated paragraph" typo.

Docs (Enterprise): Add in-page link to vault usage and fix typo

---

content/deploy/cli-command-reference.md

**This PR is a rehash of #165 which had merge conflicts**
Adds documentation for the new `--cache` superflag, as per [PR #7652](https://github.com/dgraph-io/dgraph/pull/7652).
Addresses [DOC-249](https://dgraph.atlassian.net/browse/DOC-249).
[Preview](https://deploy-preview-165--dgraph-docs-repo.netlify.app/deploy/cli-command-ref/).

docs(superflags): Add documentation for --cache superflag

---

content/deploy/cli-command-reference.md
content/design-concepts/raft.md

* Adds documentation for the new `snapshot-after-duration` option of `--raft`
* Renaming of `snapshot-after` to `snapshot-after-entries`
As per [PR #7675](https://github.com/dgraph-io/dgraph/pull/7675).
Addresses [DOC-250](https://dgraph.atlassian.net/browse/DOC-250).

docs(flags): Add documentation for --raft superflag's changed options

---

content/mutations/json-mutation-format.md

Added double quotes (`""`) for facet syntax in RDF. 
Wrong syntax:
```
_:blank-0 <name> "Carol" (initial=C) .
```
Correct syntax:
```
_:blank-0 <name> "Carol" (initial="C") .
```

Double quotes missing in RDF format for facets

---

content/deploy/fast-data-loading/live-loader.md
content/enterprise-features/multitenancy.md

this PR fixes some wrong statements/commands in our current multi-tenancy doc
(cherry picked from commit 7d124c79f63f2863a35f29db4308d1c1d71fc2c5)

Multi-tenancy fixes (#179)

---

content/mutations/json-mutation-format.md

Added double quotes (`""`) for facet syntax in RDF. 
Wrong syntax:
```
_:blank-0 <name> "Carol" (initial=C) .
```
Correct syntax:
```
_:blank-0 <name> "Carol" (initial="C") .
```
(cherry picked from commit 9d6445a0e736d233cf4f6f063e345ea0e35c7180)

[Cherry-pick] Added double quotes on rdf format for facets (#183)

---

content/deploy/tls-configuration.md
content/design-concepts/minimizing-network-calls.md
content/howto/jepsen-tests.md
content/query-language/fragments.md

Per DOC-274
Cherry-pick to 21.03 and 20.11

Docs (chore) Fixing 404s

---

content/deploy/single-host-setup.md
content/dgraph-overview.md

on https://dgraph.io/docs/deploy/single-host-setup/ the "Run using Docker" section has notice which is not rendered correctly due to typo. Refer to attached screenshot

Docs(Other): fix notice tag typo

---

README.md
config.toml
netlify.toml
scripts/build.sh

Drop Docs Build for EOL v20.03 per @danielmai 
Upgrade hugo to build with version 0.79.0
Add site param to hugo config for docs site repo
Add disableKinds and ignoreErrors to quiet hugo builds for unwanted taxonomy pages
This needs picked to: 
- `master`, 
- `release/v21.03`, 
-  `release/v20.11`, 
-  `release/v20.07`
Merging this PR is prep work for:
https://github.com/dgraph-io/hugo-docs/pull/97
This also drops 20.03 docs in the build script. Not sure if we want to add a redirect for existing links to v20.03 docs to a landing page that states what versions are supported instead of 404 pages.

Docs (Chore) Dependent on Merge Themes

---

README.md
config.toml
netlify.toml
scripts/build.sh

* Chore: Dependent on Merge Themes
Drop Docs Build for EOL v20.03 per dmai
Upgrade hugo to build with version 0.79.0
Add site param to hugo config for docs site repo
Add disableKinds and ignoreErrors to quiet hugo builds for unwanted taxonomy pages
This needs picked to master, release/v21.03, release/v20.11, and release/v20.07
* update readme to change hugo version

Docs (Chore) Dependent on Merge Themes (#186)

---

content/deploy/single-host-setup.md
content/ratel/backups.md
content/ratel/cluster.md
content/ratel/connection.md
content/ratel/console.md
content/ratel/overview.md
content/ratel/schema.md

A Dgraph user requested that we link from Dgraph Docs to instructions for cloning and building Ratel. This PR adds links to those instructions, removes a non-functional Docker command to run Ratel, and adds a Ratel overview.
Fixes DOC-280

Docs (Ratel): Link to instructions to clone and build locally, add "Ratel Overview"

---

content/query-language/graphql-fundamentals.md

The DQL docs use the film dataset. We should include in these docs the film dataset schema, which can be found at https://dgraph.io/tour/moredata/1/
Fixes DOC-2

Docs (DQL): Include the movie database schema in DQL reference

---

content/deploy/dgraph-zero.md

docs(fix): Fix variable names in dgraph-zero.md

---

content/deploy/fast-data-loading/bulk-loader.md

This pr explains how to properly use a `p` directory that is coming from a different cluster. This adds instruction on how to let Zero correctly manage the `p` directory by increasing the timestamp

Add information about using "p" dir coming from other Dgraph clusters

---

content/graphql/lambda/field.md
content/graphql/lambda/overview.md

Repairing PR from #127 since that original branch was deleted from a forked repo and could no longer modify it.
- add authHeader example for returning Boolean `Author.isMe`
- normalize indentation of files changed
- add `authHeader` definition including TS definitions in lambda overview
- add example for calling `graphql` function in lambda with custom authHeader (JWT)
- fixed TS syntax
- clarified some of the TS variables using longer names such as replacing `s` with `query` where the string is a query string and there is no need for smaller verbosity in documentation.

Docs (GraphQL) Document lambda authHeader

---

content/graphql/lambda/mutation.md
content/graphql/lambda/query.md
content/graphql/schema/reserved.md

docs(graphql): Add note regarding lambda mutation prefixes

---

content/graphql/todo-app-tutorial/deploy.md

I noticed two different authorization formats were used in the tutorial.
I changed the old format to the new format that is shown on this page. https://dgraph.io/docs/graphql/todo-app-tutorial/todo-firebase-jwt/

Docs (GraphQL) Match the new authorization format for the schema

---

scripts/build.sh

Per CTO feedback, "master" should be the last entry in the version selector on dgraph.io/docs

Update build.sh to move 'master' to the end of the list of build versions

---

scripts/local.sh

This gets the latest version for local and preview builds. Before this version tag was being set in the build script, but a preview deployment or local build using the local.sh script was not adding in the version variable needed for the version shortcode.

DOCS (chore) add CURRENT_LATEST_TAG variable to local (preview) builds

---

content/graphql/custom/directive.md

Noticed some ambiguity and felt a bit unclear in the `@custom` docs. This PR tries to: 
* improve how the docs describe `introspectionHeaders` and
* better describe how `Authorization` header in an endpoint request can take a value from `Dgraph.Secret`.

chore(graphql): Minor polishing to @custom docs

---

content/query-language/cascade-directive.md

docs(dql): Add note to parameterized cascade

---

content/graphql/queries/and-or-not.md

fix syntax error, normalize indention, and add notice about combining nested filters

Docs (GraphQL) fix nested filter syntax error

---

content/query-language/multiple-query-blocks.md

add example for multiple var blocks in single query, and add notice of alternative way to combine var blocks

Docs (DQL) add multiple var blocks example

---

content/graphql/lambda/webhook.md

Fixes DOC-354
References:
- https://discuss.dgraph.io/t/add-webhook-on-deep-mutations/13874
- https://discuss.dgraph.io/t/bug-lambdaonmutate-not-called-when-type-is-added-through-parents-add-mutation/14547

Docs (GraphQL/Lambda) add notice concerning deep webhooks

---

content/dgraph-overview.md

These improvements are based off from user feedback and requests for more context to be added to the docs for new users, mainly related to https://discuss.dgraph.io/t/new-to-dgraph-dql-vs-graphql-endpoints-headers-and-schema-translation/10443
Linked "DQL vs GraphQL" blog article for a reference to not duplicate all of that information again.
Fixes DOC-268

Docs (Dgraph) Improve Dgraph Overview

---

content/graphql/queries/search-filtering.md

I missed this requirement when reading this page, so I couldn't understand why I got weird errors like "Field "virtualEventUrl" is not defined by type EventFilter." I understood it after getting help in the forums. https://discuss.dgraph.io/t/how-do-you-create-parameterized-graphql-queries/14711 Hopefully this will prevent others from making the same mistake.

Docs(GraphQL): Emphasize that @search annotation is required for filtering on predicates

---

content/howto/lambda-webhooks-example.md

It is a common need to populate a "Created At" date whenever a new data is created. Using Lambda Webhooks, the population of this field can be offloaded from the clients to a Dgraph Lambda. In this example, we will use a special feature called Lambda Webhooks. Lambda Webhooks are special kind of lambdas that are automatically invoked whenever a GraphQL type is added, modified or deleted.
This PR contains a complete example.

An example of using Lambda Webhooks

---

content/graphql/lambda/server.md

When reading the docs I tried setting the graphql-lambda-server according to the docs.
`DGRAPH_ALPHA_GRAPHQL_LAMBDA_URL: "http://dgraph_lambda:8686/graphql-worker"`
This however did not work and I did some digging discovering that the actual format of this environment variable should be
`DGRAPH_ALPHA_GRAPHQL: "lambda-url=http://dgraph_lambda:8686/graphql-worker"`
So to avoid others also making this mistake I made a PR to update the docs.
link to the forum post: https://discuss.dgraph.io/t/running-dgraph-standalone-along-with-dgraph-dgraph-lambda/14421/6?u=erbo_engineering

Docs(lambda-server): Add correct lambda-url style

---

content/enterprise-features/access-control-lists.md
content/enterprise-features/multitenancy.md

Modified pages for Access Control Lists and Multi-Tenancy outlining the process to define access rules over all predicates that exist in a particular namespace. 
The changes pertain to the new feature introduced as per [this Dgraph PR](https://github.com/dgraph-io/dgraph/pull/7991)

Docs(ACL and Multi-Tenancy): Modify pages to include info about managing access for all predicates

---

content/deploy/production-checklist.md

Adding a note about our suggestion for CPU clock speed to be equal to 3.4GHz when running dgraph self-hosted to avoid high CPU usage

docs(prod-checklist): Add suggestion for CPU clock speed

---

content/graphql/queries/order-page.md

This page kind of made it sound like the order parameter was required, but the `first` and `offset` params can be used without it, so this PR clarifies it.

Docs(GraphQL): Say the order parameter is not required for pagination

---

content/deploy/tls-configuration.md

The examples provided in the documentation for `--tls` will not work without quotes surrounding the value. I discovered this when upgrading our servers from v20.09 to v21.03.
This patch simply corrects the examples provided.

Docs(Deploy): Fix --tls syntax examples

---

content/deploy/tls-configuration.md

Cherry-pick of #273:
> The examples provided in the documentation for --tls will not work without quotes surrounding the value. I discovered this when upgrading our servers from v20.09 to v21.03.
> 
> This patch simply corrects the examples provided.

docs(Deploy): Fix --tls syntax (#273)

---

scripts/build.sh

Along with https://github.com/dgraph-io/hugo-docs/pull/109, update the build script to build docs for the Dgraph v21.12 Zion release.
* Ignore v20.07 docs

chore: Update build script for latest release.

---

content/migration/migrate-tool.md

The properties file format is not accepted anymore (at least not by v21.12.0).

Docs(Dgraph): Update migrate tool config file format

---

content/query-language/cascade-directive.md

Noticed a couple of minor typos while reading through the [`@cascade` directive reference page](https://dgraph.io/docs/query-language/cascade-directive/), thought I'd submit a quick PR to fix them.
Thanks!

fixed minor typos in cascade-directive

---

content/enterprise-features/audit-logs.md

Documentation provides incorrect flag.  See L57-75 in ee/audit/run_ee.go.

Docs(audit): fix flag for dgraph audit decrypt

---

content/enterprise-features/audit-logs.md

In dgraph/cmd/zero/run.go  around L230, `Zero.Conf.GetString("audit")` only parses first subflag.
E.g. `dgraph zero --audit output=audit-log-dir;compress=false;encrypt-file=enc-key` is parsed as output=audit-log-dir, omitting the later arguments.  I have run into this issue here but it is possibly a more general issue for superflags like alpha, zero, etc.  An easy fix is to use quotes:
`dgraph zero --audit "output=audit-log-dir;compress=false;encrypt-file=enc-key"`

docs(audit): Update audit-logs.md

---

content/clients/go.md

Reference https://github.com/dgraph-io/dgraph-docs/pull/284
dgo.DialCloud() is available since dgo/v210
>This release works for dgraph versions >= 21.03. This version adheres to the contract of multi-tenancy.

Docs(Go Clients): install dgo/v210 instead of dgo/v200.

---

content/deploy/download.md
content/deploy/multi-host-setup.md
content/deploy/single-host-setup.md
content/dgraph-overview.md
content/get-started/index.md
content/tutorial-1/index.md

ref: https://github.com/dgraph-io/dgraph-docs/pull/249
ref: https://github.com/dgraph-io/dgraph-docs/pull/262
>Remove the ratel command due to deprecation of its binary in the main build.
>We no longer include Ratel in Dgraph Docker images. This PR addresses that with updated information on how to use Ratel in the [Get Started](https://dgraph.io/docs/get-started/) guide.
Fix #300

docs(Ratel): Update Ratel information across all docs.

---

content/enterprise-features/access-control-lists.md

Fixes: https://github.com/dgraph-io/dgraph-docs/issues/305
page: https://dgraph.io/docs/enterprise-features/access-control-lists/

[Docs] Access Control Lists : add the command and random keys

---

content/enterprise-features/encryption-at-rest.md

- added a note about the command for macOS and the command to view the key.
- updated the key in the example
Fixes: https://github.com/dgraph-io/dgraph-docs/issues/304

[Docs] Encryption at Rest: added a note for macOS

---

content/releases/index.md

- Update the Releases page with the latest release, Dgraph v22.0.0
- Update the previous versions' patch release information.
- Remove support for  v21.12.x,  v21.03.x, v20.07 and v20.11.
- Set v21.12.x as discontinued
Fix #329

docs(release): Dgraph v22.0.0 release

---

content/deploy/production-checklist.md

A couple times people have added 1.1TB of data to a single Dgraph Alpha and recieved "base level can't be zero" as a slightly cryptic error. This is by design since the default level config only allows 1.1TB in the seven levels initially configured. This change adds minimal language to clarify the situation, so people can at least know the limit and which parameters to alter.
See issue here https://discuss.dgraph.io/t/panic-base-level-cant-be-zero/15715/6

Docs(deploy): Clarify options needed for more than 1.1TB per instance

---

content/tutorial-8/index.md

1. fix a typo error in the [DQL tutorial-8](https://dgraph.io/docs/tutorial-8/) about geo data. the filter argument in the code sample, "`hotel`" is changed to "`Hotel`" in consistent with the given sample data.
```go
1571 - has_type @filter(eq(loc_type, "hotel")){
1571 + has_type @filter(eq(loc_type, "Hotel")){
```

Docs(other): fix a typo error, change DQL filter argument value "hotel" to "Hotel".

---

content/deploy/dgraph-administration.md

Fixes: https://github.com/dgraph-io/dgraph-docs/issues/310
Updated the list of admin endpoints
Note: Create and edit docs in the `main` branch when you can, so that we only cherry-pick out of `main`, not into `main`.
-->

[update] Admin API endpoints

---

.github/CODEOWNERS
netlify.toml

testing different option for the Algolia crawler.

re-testing with customDomain

---

netlify.toml
scripts/branchdeploy.sh

try a new script to deploy release branches and trigger algolia

change build script for branches

---

content/howto/exportdata/export-data.md

typo "aphla -> alpha"

---

content/dql/type-system.md
content/howto/giving-nodes-type.md
content/mutations/json-mutation-format.md
content/query-language/expand-predicates.md
content/tutorials/index.md

Move type-system as a concept page in DQL rather than a part of the DQL syntax.
type system will be referenced in DQL syntax page when explaining why you may have "dgraph.type" predicate in mutation.

move type-system

---

content/clients/java.md
content/clients/javascript/grpc.md
content/clients/python.md
content/deploy/dgraph-administration.md
content/deploy/dgraph-alpha.md
content/design-concepts/concepts.md
content/dql/predicate-types.md
content/dql/type-system.md
content/enterprise-features/access-control-lists.md
content/graphql/dgraph/index.md
content/mutations/language-rdf-types.md
content/query-language/count.md
content/query-language/facets.md
content/query-language/functions.md
content/query-language/sorting.md

update all references and use shorter reference.

[REVAMP]: move predicate types (ex schema) to DQL section

---

content/clients/java.md
content/clients/javascript/grpc.md
content/clients/python.md
content/deploy/dgraph-administration.md
content/deploy/dgraph-alpha.md
content/design-concepts/concepts.md
content/dql/predicate-types.md
content/dql/type-system.md
content/enterprise-features/access-control-lists.md
content/graphql/dgraph/index.md
content/mutations/language-rdf-types.md
content/query-language/count.md
content/query-language/facets.md
content/query-language/functions.md
content/query-language/sorting.md

[REVAMP} - move predicate types (ex schema) to DQL section

---

content/_index.md
content/graphql/_index.md

revamp doc home

---

content/dql/predicate-indexing.md
content/dql/predicate-types.md
content/dql/type-system.md
content/howto/dql-schema-request.md
content/howto/update-dgraph-types.md

predicate pages was overloaded with info about indexing, qurying the schema, updating the schema and predicate concepts.
Clarify and create separate pages.

Split info from the predicate page

---

content/query-language/cascade-directive.md

Noticed a couple of minor typos while reading through the [`@cascade` directive reference page](https://dgraph.io/docs/query-language/cascade-directive/), thought I'd submit a quick PR to fix them.
Thanks!

fixed minor typos in cascade-directive (#291)

---

content/graphql/custom/directive.md

Noticed some ambiguity and felt a bit unclear in the @custom docs. This PR tries to:
improve how the docs describe introspectionHeaders and
better describe how Authorization header in an endpoint request can take a value from Dgraph.Secret.

chore(graphql): Minor polishing to @custom docs (#228)

---

content/dql/predicate-indexing.md

This replaces https://github.com/dgraph-io/dgraph-docs/pull/378

Docs(DQL): Fix errors in the reverse edge description in the schema MD

---

content/deploy/admin/metrics.md

> This renames the Badger metrics in the /metrics endpoint to remove the
> Badger version in the metric names. This allows the metric name to
> remain the same across Badger major versions.
> 
> | Previous Name                   | New Name                     |
> | ------------------------------- | ---------------------------- |
> | badger_v3_disk_reads_total      | badger_disk_reads_total      |
> | badger_v3_disk_writes_total     | badger_disk_writes_total     |
> | badger_v3_read_bytes            | badger_read_bytes            |
> | badger_v3_written_bytes         | badger_written_bytes         |
> | badger_v3_lsm_bloom_hits_total  | badger_lsm_bloom_hits_total  |
> | badger_v3_gets_total            | badger_gets_total            |
> | badger_v3_puts_total            | …

Docs(Metrics): Fix metrics

---

content/dql/dql-syntax/json-mutation-format.md

Noticed a minor typo when reading through the JSON mutation docs, thought I'd submit a quick PR to fix it.
Thanks!

docs(typo): fixed typo in JSON mutation docs

---

content/enterprise-features/binary-backups.md

Simple typo fix.
---
Might be nice to add an example of how to use the /admin endpoint?
Like:
```
curl -X POST localhost:8080/admin -H "Content-type: application/graphql" --data-binary '@admin-mutation'
```
File admin-mutation:
```
mutation{
restore(input:{
location: "/dgraph/backup",
backupId: "ecstatic_germain2"
}){
message
code
}
}
```

Docs (Binary backups): Online restore, remove rouge '

---

content/graphql/schema/graph-links.md

This PR fixes a simple typo in the docs.

Docs(Other): Fix typo

---

content/deploy/admin/dgraph-administration.md

Fix typo `mutation=strict` -> `mutations=strict`

Docs(other): Fix mutations=strict typo in dgraph-administration.md

---

content/dql/clients/unofficial-clients.md

Added dgraph4net C# Unofficial client
- In past, under v20, it's is present, but not commited to new
- In the new version of dgraph4net, only .NET 7+ is supported
- v23 are supported
- Migrations are supported with Dgraph4Net.Tools
- Lower size compared to old version
- Now we use Fluent mapping instead of Attributes mapping
- Better performance to mapping
- Mapping is used to serialize / deserialize DQL responses
Our documentation for checking [https://github.com/schivei/dgraph4net/blob/master/README.md](https://github.com/schivei/dgraph4net/blob/master/README.md)

Docs(Unofficial Clients): added new C# unofficial client

---

content/dql/dql-syntax/dql-rdf.md

Escape references to words "subject" and "object" so they render visibly in generated documentation

Docs(Other): escape angle brackets for visible rendering of important text

---

content/deploy/admin/dgraph-administration.md
content/deploy/cli-command-reference.md
content/deploy/dgraph-alpha.md
content/deploy/security/tls-configuration.md

The PR https://github.com/dgraph-io/dgraph/pull/8554 removes these two endpoints.

remove reference to /admin/{backup,export} endpoints

---

content/dgraph-glossary.md

There's a tiny formatting issue in dgraph-glossary.md. This fixes it

Docs(dgraph-glossary.md): Fixed hyperlink formatting in GraphQL section

---

content/query-language/pagination.md

This adds notes about complexity of `offset` and `after`.
Some observations can be found at https://discuss.dgraph.io/t/pagination-with-offset-should-scale-like-after/8577.

Docs(DQL): Add note about complexity of offset and after

---

content/graphql/quick-start/index.md

Indentation was off, causing rendering issues on https://dgraph.io/docs/graphql/quick-start/

Docs(GraphQL): Fix indentation on graphql sample

---

content/releases/index.md

Updating the release table in docs to:
1. include the latest release (v23.1)
2. make the table more maintainable/default current
3. omit patch releases

Update release table

---

content/graphql/schema/types.md

Fixes a minor typo in the documentation.

Docs(GraphQL): Fix typo "directory" vs "directive"

---

content/graphql/security/_index.md

Changed the note (in a box) to say security is on for cloud. Also fixed typo.

Update _index.md to clarify cloud security on by default

---

content/enterprise-features/binary-backups.md

Description:
The offline restore feature is deprecated (v21.03.0 was the last version to have it), but it is not stated in the docs, which might confuse readers. So, I think we should do something to notify of this change.

Docs(Enterprise): Notify that offline restore feature is deprecated

---

content/dql/dql-get-started.md

While following the https://dgraph.io/docs/dql/dql-get-started#step-4-alter-schema documentation I noticed that the described type for `release_date` was of type `date` not `datetime`.
It appears that in later versions of the Ratel UI (or perhaps it's always been?) `date` is now `datetime`. 
This PR modifies the documentation from `date` to `datetime`.
This is my first contribution to the dgraph docs repo, please let me know if there's anything else I can do to make this a better PR! 
Many thanks!

docs(dql): Updated schema alter from date, to datetime

---

content/deploy/cli-command-reference.md

Remove references to raft migrate in the CLI.
Fixes: https://github.com/dgraph-io/dgraph-docs/issues/600
Description: Please include the following in your PR description:
1. A brief, clear description of the change.
2. Link to any related PRs or discuss.dgraph.io posts.
3. If this PR corresponds to a JIRA issue, include "Fixes DOC-###" in the PR description.
3. If this is a breaking change, please put "[Breaking]" in the title. In the description, please put a note with exactly who these changes are breaking for.
4. If you are creating a PR in `main` and you know it needs to be cherry-picked to a release branch, please mention that in your PR description (for example: "cherry-pick to v20.07"). Cherry-pick PRs should reference the original PR.
Note: Create and edit docs in the `main` …

[Docs] Dgraph CLI Reference

---

content/graphql/lambda/overview.md

Corrrect of defining a Type in GraphQL Response

---

content/releases/index.md

Docs(other) update Releases table

---

content/howto/exportdata/export-data-cloud.md

- Added information on running namespace-specific exports on Dgraph Cloud.
- Other minor corrections and edits to existing instructions.

Docs(Cloud): Update instructions for namespace-specific exports.

---

content/graphql/schema/types.md

- Updated the Graphql "Types" section to remove examples wrt the in-built geolocation type `Pointlist`, as it is unsupported. 
- Other minor edits wrt indentation etc.

Docs(Graphql): Remove examples citing the unsupported geolocation type "Pointlist".

---

content/graphql/schema/directives/_index.md

Description:
@id doc URL syntax has an extra parenthesis.

Fix @id directive MD URL syntax error

---

content/dql/clients/go.md

Topic: Docs(Other): Remove redundant word `to` in the documentation
Description:
The word `to` in the documentation was redundant.
```diff
- This is an example from the [GoDoc](https://godoc.org/github.com/dgraph-io/dgo). It shows how to to create a `Node` with name `Alice`, while also creating her relationships with other nodes. 
+ This is an example from the [GoDoc](https://godoc.org/github.com/dgraph-io/dgo). It shows how to create a `Node` with name `Alice`, while also creating her relationships with other nodes.
```
The link to the page is: https://dgraph.io/docs/dql/clients/go/

chore(Other): Remove redundant word in go.md

---

content/dql/clients/go.md

Topic: Docs(Other): Fix the grammatical error in the documentation
Description:
1. The sentence in the documentation was grammatically incorrect and was causing confusion
```diff
- a string representing the valid RDF triples (one per line) to added or removed
+ a string representing the valid RDF triples (one per line) to be added or removed
```
The link to the page is: https://dgraph.io/docs/dql/clients/go/

chore(Other): Update go.md in dgraph docs
